import "~/styles/globals.css";

import { Reddit_Mono } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
import { TRPCReactProvider } from "~/trpc/react";

const redditMono = Reddit_Mono({
	subsets: ["latin"],
});

export const metadata = {
	title: "Create T4 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${redditMono.className}`}>
			<body>
				<ClerkProvider>
					<TRPCReactProvider>{children}</TRPCReactProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
